# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLYVOnX8FpED_0X6bA7hb-SF-F1GtdHo
"""

import pandas as pd
df = pd.read_excel('/content/customer_shopping_behavior.xlsx')

df.head()

df.info()

df.describe(include='all')

df.isnull().sum()

df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

df.isnull().sum()

df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

df.columns

# create age category column
labels = ['Young adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels = labels)

df[['age','age_group']].head(10)

#purchase_frequency_days_column

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 months' : 90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

df[['purchase_frequency_days','frequency_of_purchases']].head(10)

df[['discount_applied','promo_code_used']].head(10)

(df['discount_applied']==df['promo_code_used']).all()

df = df.drop('promo_code_used',axis=1)

df.columns

pip install psycopg2-binary sqlalchemy

"""To install and run PostgreSQL inside the Colab environment, we'll follow these steps:
1.  Install the PostgreSQL server.
2.  Initialize the database cluster.
3.  Start the PostgreSQL service.
4.  Create a PostgreSQL user and database that matches the credentials you've specified.
"""



# Install PostgreSQL
!apt-get -y install postgresql
!service postgresql start

username = "postgres"
password = "greeshu"
host = "localhost"
port = "5432"
database = "customer_behavior"

# Setup a password for the default 'postgres' user
# This is typically needed for creating new users and databases
!sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '{password}';"

# Create a new PostgreSQL user with the specified username and password
# Note: This uses the existing `username` and `password` variables
!sudo -u postgres psql -c "CREATE USER {username} WITH PASSWORD '{password}';"

# Create the database with the specified name and assign ownership to the new user
# Note: This uses the existing `database` variable
!sudo -u postgres psql -c "CREATE DATABASE {database} OWNER {username};"

print(f"PostgreSQL user '{username}' and database '{database}' created successfully.")

"""Now that PostgreSQL is running and the database and user are set up, you can try loading the data into the database using the previously defined `engine` and `df`."""

from sqlalchemy import create_engine

# Re-using the connection parameters from before
# username = "postgres"
# password = "greeshu"
# host = "localhost"
# port = "5432"
# database = "customer_behavior"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name,engine,if_exists="replace",index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

import pandas as pd

# QUERY 1: Construct the SQL query to select all rows from the 'customer' table
query = f"SELECT * FROM {table_name} limit (20)"

# Execute the query using pandas.read_sql and the existing engine
queried_df = pd.read_sql(query, engine)

print(f"Successfully queried data from the '{table_name}' table:")
display(queried_df.head())

import pandas as pd

# Query 2: What is the total revenue generated by male vs. female
query_gender_revenue = "SELECT gender, SUM(purchase_amount) AS total_revenue FROM customer GROUP BY gender;"

# Execute the query using pandas.read_sql and the existing engine
gender_revenue_df = pd.read_sql(query_gender_revenue, engine)

print("Total revenue generated by male vs. female:")
display(gender_revenue_df)

#QUERY 3 which customers used a discount but still spent more than the average purchaSE AMOUNT
import pandas as pd

# Calculate the average purchase amount and then filter for customers
# who received a discount and spent more than this average.
query_discount_high_spend = """
SELECT
    customer_id,
    gender,
    purchase_amount,
    discount_applied
FROM
    customer
WHERE
    discount_applied = 'Yes'
    AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer);
"""

# Execute the query
discount_high_spend_df = pd.read_sql(query_discount_high_spend, engine)

print("Customers who used a discount and spent more than the average purchase amount:")
display(discount_high_spend_df.head())

import pandas as pd

# Query 4 :  top 5 products with highest average review rating
query_top_products = """
SELECT
    item_purchased,
    AVG(review_rating) AS average_review_rating
FROM
    customer
GROUP BY
    item_purchased
ORDER BY
    average_review_rating DESC
LIMIT 5;
"""

# Execute the query
top_products_df = pd.read_sql(query_top_products, engine)

print("Top 5 products with the highest average review rating:")
display(top_products_df)

#COMPARE THE AVERAGE PURCHASE AMOUNT BETWEEN STANDARD SHIPPING AND EXPRESS SHIPPING
import pandas as pd

# Query 6 : to compare average purchase amount by shipping type
query_shipping_purchase = """
SELECT
    shipping_type,
    AVG(purchase_amount) AS average_purchase_amount
FROM
    customer
GROUP BY
    shipping_type
ORDER BY
    average_purchase_amount DESC;
"""

# Execute the query
shipping_purchase_df = pd.read_sql(query_shipping_purchase, engine)

print("Average purchase amount by shipping type:")
display(shipping_purchase_df)

display(shipping_purchase_df)

import pandas as pd

# Query 7: to compare average purchase amount and total revenue by subscription status
query_subscription_spend = """
SELECT
    subscription_status,
    AVG(purchase_amount) AS average_purchase_amount,
    SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY
    subscription_status
ORDER BY
    total_revenue DESC;
"""

# Execute the query
subscription_spend_df = pd.read_sql(query_subscription_spend, engine)

print("Average purchase amount and total revenue by subscription status:")
display(subscription_spend_df)



import pandas as pd

# Query 8 : to find the top 5 products with the highest percentage of discounts applied
query_top_discounted_products = """
SELECT
    item_purchased,
    CAST(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) AS FLOAT) * 100 / COUNT(*) AS percentage_discount_applied
FROM
    customer
GROUP BY
    item_purchased
ORDER BY
    percentage_discount_applied DESC
LIMIT 5;
"""

# Execute the query
top_discounted_products_df = pd.read_sql(query_top_discounted_products, engine)

print("Top 5 products with the highest percentage of discounts applied:")
display(top_discounted_products_df)

#QUERY 9 : SEGMENT CUSTOMERSINTO NEW, RETURNING, LOYAL BASED ON THEIR TOTAL NUMBER OF PREVIOUS PURCHASES,AND SHOW COUNT OF EACH SEGMENT
import pandas as pd

# Query to segment customers based on previous purchases and count each segment
query_customer_segmentation = """
SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New Customer'
        WHEN previous_purchases BETWEEN 2 AND 25 THEN 'Returning Customer'
        WHEN previous_purchases > 25 THEN 'Loyal Customer'
        ELSE 'Unknown'
    END AS customer_segment,
    COUNT(customer_id) AS number_of_customers
FROM
    customer
GROUP BY
    customer_segment
ORDER BY
    number_of_customers DESC;
"""

# Execute the query
customer_segmentation_df = pd.read_sql(query_customer_segmentation, engine)

print("Customer segmentation based on previous purchases:")
display(customer_segmentation_df)

import pandas as pd

# Query 10: Find the top 3 most purchased products within each category
query_top_products_by_category = """
WITH RankedProducts AS (
    SELECT
        category,
        item_purchased,
        COUNT(item_purchased) AS purchase_count,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(item_purchased) DESC) as rn
    FROM
        customer
    GROUP BY
        category, item_purchased
)
SELECT
    category,
    item_purchased,
    purchase_count
FROM
    RankedProducts
WHERE
    rn <= 3
ORDER BY
    category, purchase_count DESC;
"""

# Execute the query
top_products_by_category_df = pd.read_sql(query_top_products_by_category, engine)

print("Top 3 most purchased products within each category:")
display(top_products_by_category_df)

import pandas as pd

# Query 11: to check subscription status for repeat buyers (more than 5 purchases)
query_repeat_buyer_subscription = """
SELECT
    subscription_status,
    COUNT(customer_id) AS number_of_customers,
    CAST(COUNT(customer_id) AS DECIMAL) * 100 / (SELECT COUNT(customer_id) FROM customer WHERE previous_purchases > 5) AS percentage
FROM
    customer
WHERE
    previous_purchases > 5
GROUP BY
    subscription_status
ORDER BY
    number_of_customers DESC;
"""

# Execute the query
repeat_buyer_subscription_df = pd.read_sql(query_repeat_buyer_subscription, engine)

print("Subscription status for customers with more than 5 previous purchases:")
display(repeat_buyer_subscription_df)

# Re-upload the DataFrame to the database to include the 'age_group' column
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"DataFrame with 'age_group' column successfully re-uploaded to table '{table_name}'.")

import pandas as pd

# Query 12: Calculate the revenue contribution of each age group
query_age_group_revenue = """
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM
    customer
GROUP BY
    age_group
ORDER BY
    total_revenue DESC;
"""

# Execute the query
age_group_revenue_df = pd.read_sql(query_age_group_revenue, engine)

print("Revenue contribution by age group:")
display(age_group_revenue_df)